
<div class="main-container col2-left-layout">
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_top_home4')->toHtml(); ?>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	
	<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('Plazathemes_Featureproductslider::featureproductslider.phtml')->toHtml();?>
	
	<div class="container-inner">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_home_home4')->toHtml(); ?>
	</div>

	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('producttab.phtml')->toHtml();?>
	</div>	
	<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static-bottom-home4')->toHtml(); ?>
	
	<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('testimonial.phtml')->toHtml();?>
	
	<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
	
	<div class="container-inner">
		<div class="banner home-group-home3-bottom">
			<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate(	'subscribe.phtml')->toHtml();?>	
		</div>	
	</div>
	
</div>


