<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
if($this->getConfig('enable_frontend')):
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$image = 'category_page_grid';
	$_productHelper = $this->helper('Magento\Catalog\Helper\Product');
	$block = $this->getBlockProduct();
 
	$auto = $this->getConfig('auto');
	if($auto)
		$auto = 'true';
	else
		$auto = 'false';
	$rows = $this->getConfig('rows');
	$show_next_back = $this->getConfig('show_next_back');
	$pagination = $this->getConfig('pagination');
	if($this->getConfig('speed'))
		$speed = $this->getConfig('speed');
	else
		$speed = '3000';
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
?>
<div class="pt-randomproduct-container">
	<div class="ma-title"><h2><?php echo $this->getConfig('title') ?></h2></div>
	<ul class="ptowl">
	<?php
	$i = 0;
	 foreach($this->getProducts() as $_product)
	{
	if($i%$rows == 0):
	?>
		<li class="item">
	<?php
	endif;
			$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400)->getUrl();
		?>
		
		<div class="product-item-inner">
			<div class="pull-left">
				<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-photo"><img src="<?php echo $productImage; ?>" alt=""/></a>
			</div>
			
			<div class="media-body">
				<div class="product-name">
					<div class="title-name">
						<?php /* @escapeNotVerified */ echo __('Sample Category'); ?>
					</div>
					<strong class="product-item-name">
						<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-link"><?php echo $_product->getName() ?></a>
					</strong>	
				</div>	
				<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
				<?php echo $block->getProductPrice($_product) ?>

				<?php if ($_product->isSaleable()): ?>
					<?php $postParams = $block->getAddToCartPostParams($_product); ?>
					<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<?php echo $block->getBlockHtml('formkey')?>
						<button type="submit"
								title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
								class="action tocart primary">
							<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
						</button>
					</form>
				<?php else: ?>
					<?php if ($_product->getIsSalable()): ?>
						<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
					<?php else: ?>
						<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
	<?php if($i%$rows == $rows - 1): ?>
		</li>
	<?php
	endif;
	$i++;
	}
	?>
	</ul>
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
		$(document).ready(function(){
			$(".pt-randomproduct-container .ptowl").owlCarousel({
				<?php
					if(($auto== 'true') && $speed):
				?>
				autoPlay : <?php echo $speed; ?>,
				<?php
					endif;
				?>
				items : 1,
				itemsDesktop : [1199,1],
				itemsDesktopSmall : [992,2],
				itemsTablet: [767,2],
				itemsMobile : [479,1],
				slideSpeed : <?php echo $pagination; ?>,
				paginationSpeed : <?php echo $pagination; ?>,
				rewindSpeed : <?php echo $pagination; ?>,
				addClassActive: true,
				navigation : <?php echo $show_next_back; ?>,
				stopOnHover : true,
				pagination : <?php echo $show_navigation_control; ?>,
				scrollPerPage:true,
			});
		});
	});
</script>
<?php
endif;
?>