	<?php 
		$enable = $block->getConfig('enabled');
		if($enable < 1) return ; 
		$items = $block->getConfig('items');
		$speed = $block->getConfig('speed');
		$qty = $block->getConfig('qty');
		$showCart = $block->getConfig('addtocart');
		$showWishlist = $block->getConfig('wishlist');
		$showCompare = $block->getConfig('compare');
		$show_navigation = $block->getConfig('navigation');
		$show_pagination = $block->getConfig('pagination');
		$auto = $block->getConfig('auto');
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$rows = $block->getConfig('row');
	?>



	<div class="tab_container producttab_inner"> 
	
		<div class="group-title1 title-tab">
			<ul class="tabs">
				<?php 
					$tab_contents = $block->getTabContent() ; 
				$count=0;			
				foreach($tab_contents as $tab) {
					?>
				<li rel="tab_<?php echo $tab['id'];?>"  class="<?php if ($count==0): ?>first active<?php endif; ?>" > <?php echo $tab['name'];?></li>
					<?php
					$count ++; 
				}
				?>
			</ul>
		</div>	
	
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		

			<div class="owl-container">
			 <div id="tab_<?php echo $tab['id'];?>" class="tab_content"> 
				<div class="productTabContent owl-carousel">
							<?php 
								$i=0;
								$productItems =  $tab['productInfo']; 
								foreach($productItems as $_item) { 
										$productImage = $block->getImage($_item, $image);
								?>
									<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php $count_r = 0; } ?>
									
									<div class="item products-grid">
										<div class="item-inner">
										
											<div class="image-container product-item-info">
												<?php
													$newFromDate = $_item->getNewsFromDate();
													$newToDate = $_item->getNewsToDate();                
													$now = date("Y-m-d H:m:s");
													// Get the Special Price
													$specialprice = $_item->getSpecialPrice(); 
													// Get the Special Price FROM date
													$specialPriceFromDate = $_item->getSpecialFromDate();
													// Get the Special Price TO date
													$specialPriceToDate = $_item->getSpecialToDate();
													// Get Current date
													if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
													$_savePercent = 100 - round(($_item->getSpecialPrice() / $_item->getPrice())*100);
													echo "<span class='hot-sale'>sale</span>";
													}else{
													if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
													?>
													<div class="label-pro-new"><span><?php echo __('new') ?></span></div>
													<?php
													}
													}
												?>
												<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
												<?php echo $productImage->toHtml() ?>
												</a>
												<div class="product-item-details">
													<div class="product-name">
														<div class="title-name">
															<?php /* @escapeNotVerified */ echo __('Sample Category'); ?>
														</div>
														<strong class="product-item-name">
															<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
															   href="<?php echo $block->getProductUrl($_item) ?>"
															   class="product-item-link">
																<?php echo $block->escapeHtml($_item->getName()) ?>
															</a>
														</strong>
													</div>
													 <?php if ($templateType): ?>
														<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
													<?php endif; ?>
													 <?php
														echo $block->getProductPrice($_item);
													 ?>
												</div>
												
												<div class="box-hover">
														<?php if ($showCart): ?>
															<div class="actions-primary">
																<?php if ($_item->isSaleable()): ?>
																	<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																		<button class="action tocart primary"
																				data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																				type="button" title="<?php echo __('Add to cart') ?>">
																			<span><?php echo __('Add to cart') ?></span>
																		</button>
																	<?php else: ?>
																		<?php
																			$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																			$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																		?>
																		<button class="action tocart primary"
																				data-post='<?php echo $postData; ?>'
																				type="button" title="<?php echo __('Add to cart') ?>">
																			<span><?php echo __('Add to cart') ?></span>
																		</button>
																	<?php endif; ?>
																<?php else: ?>
																	<?php if ($_item->getIsSalable()): ?>
																		<div class="stock available"><span><?php echo __('In stock') ?></span></div>
																	<?php else: ?>
																		<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
																	<?php endif; ?>
																<?php endif; ?>
															</div>
														<?php endif; ?>
														<?php if ($showWishlist || $showCompare || $showCart): ?>
														
															
															<?php if ($showWishlist || $showCompare): ?>
																<div class="add-to-links actions-secondary" data-role="add-to-links">
																	<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
																		<a href="#"
																		   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
																		   class="action towishlist" data-action="add-to-wishlist"
																		   title="<?php echo __('Add to Wishlist') ?>">
																			<span><?php echo __('Wishlist') ?></span>
																		</a>
																	<?php endif; ?>
																	<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
																		<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
																		<a href="#" class="action tocompare"
																		   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
																		   title="<?php echo __('Add to Compare') ?>">
																			<span><?php echo __('Compare') ?></span>
																		</a>
																	<?php endif; ?>
																</div>
															<?php endif; ?>
													
													<?php endif; ?>
												</div>
											</div>
										</div>	
									</div>
									
									 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
								<?php 
								}
								?>
						</div>
						</div>
			</div> 

		
		<?php 
		} 
		?>
	</div>

	
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){

	$(".tab_content").hide();
	$(".tab_content:first").show(); 
	$("ul.tabs li").removeClass("active");
	$("ul.tabs li:first-child").addClass("active");
	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active");
		$(this).addClass("active");
		$(".tab_content").hide();
		$(".tab_content").removeClass("animate1");
		var activeTab = $(this).attr("rel"); 
		$("#"+activeTab) .addClass("animate1");
		$("#"+activeTab).fadeIn(); 
	});
	
	  $(".productTabContent").owlCarousel({
	    		items : <?php if($items) { echo $items; } else { echo 5; }?>,
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : true,
				stopOnHover : true,
				pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
				pagination : false,
				itemsDesktop : [1199,3],
				itemsDesktopSmall : [992,3],
				itemsTablet: [767,2],
				itemsMobile : [460,1],
				addClassActive: true,
				afterAction : function() {
					$('.item-inner').removeClass().addClass('item-inner');
					$('.productTabContent .owl-item.active:first').addClass('first');
					$('.productTabContent .owl-item.active:last').addClass('last');
				}
	});
	

});

</script> 
